-- ============================================
-- SEED DATA - 100 Productos para InventoryDB
-- Ejecutar manualmente en MySQL
-- ============================================

INSERT INTO products (product_name, product_description, product_price, product_category, product_stock, created_at, updated_at) VALUES
-- === ELECTRÓNICA (20) ===
('Laptop Dell XPS 15', 'Laptop ultradelgada con pantalla OLED 3.5K, Intel Core i9, 32GB RAM', 1899.99, 'Electrónica', 18, NOW() - INTERVAL 30 DAY, NOW()),
('MacBook Air M3', 'Laptop Apple con chip M3, 16GB RAM, 512GB SSD, pantalla Liquid Retina', 1299.00, 'Electrónica', 25, NOW() - INTERVAL 28 DAY, NOW()),
('Monitor Samsung 4K 32"', 'Monitor UHD 4K IPS, 60Hz, USB-C, HDR10, ideal para diseño', 449.99, 'Electrónica', 30, NOW() - INTERVAL 25 DAY, NOW()),
('Teclado Mecánico Keychron K8', 'Teclado mecánico inalámbrico, switches Gateron Brown, RGB', 89.99, 'Electrónica', 55, NOW() - INTERVAL 20 DAY, NOW()),
('Mouse Logitech MX Master 3S', 'Mouse ergonómico inalámbrico, sensor 8000 DPI, USB-C', 99.99, 'Electrónica', 42, NOW() - INTERVAL 18 DAY, NOW()),
('Auriculares Sony WH-1000XM5', 'Auriculares over-ear con cancelación de ruido activa, 30h batería', 349.99, 'Electrónica', 35, NOW() - INTERVAL 15 DAY, NOW()),
('iPad Pro 12.9" M2', 'Tablet Apple con chip M2, pantalla Liquid Retina XDR, 256GB', 1099.00, 'Electrónica', 20, NOW() - INTERVAL 12 DAY, NOW()),
('Samsung Galaxy S24 Ultra', 'Smartphone con S Pen, cámara 200MP, 512GB, Snapdragon 8 Gen 3', 1199.99, 'Electrónica', 15, NOW() - INTERVAL 10 DAY, NOW()),
('Webcam Logitech Brio 4K', 'Webcam profesional 4K HDR con autoenfoque y corrección de luz', 169.99, 'Electrónica', 40, NOW() - INTERVAL 8 DAY, NOW()),
('Disco SSD Samsung 990 Pro 2TB', 'SSD NVMe M.2 PCIe 4.0, velocidad lectura 7450 MB/s', 179.99, 'Electrónica', 60, NOW() - INTERVAL 5 DAY, NOW()),
('Cargador Anker 100W GaN', 'Cargador USB-C compacto GaN II con 4 puertos, carga rápida', 69.99, 'Electrónica', 80, NOW() - INTERVAL 45 DAY, NOW()),
('Hub USB-C Satechi 7 en 1', 'Hub multipuerto con HDMI 4K, USB-A, SD, Ethernet', 79.99, 'Electrónica', 45, NOW() - INTERVAL 40 DAY, NOW()),
('Parlante JBL Charge 5', 'Altavoz Bluetooth portátil, resistente al agua IP67, 20h batería', 149.99, 'Electrónica', 38, NOW() - INTERVAL 35 DAY, NOW()),
('Kindle Paperwhite 2024', 'E-reader con pantalla antirreflejos de 6.8", 16GB, resistente al agua', 149.99, 'Electrónica', 50, NOW() - INTERVAL 22 DAY, NOW()),
('Apple Watch Series 9', 'Smartwatch con chip S9, pantalla siempre activa, GPS + Cellular', 429.00, 'Electrónica', 22, NOW() - INTERVAL 14 DAY, NOW()),
('Router ASUS RT-AX86U Pro', 'Router WiFi 6 gaming, doble banda, AiMesh, seguridad AiProtection', 249.99, 'Electrónica', 28, NOW() - INTERVAL 50 DAY, NOW()),
('Impresora HP LaserJet Pro', 'Impresora láser monocromática, WiFi, impresión doble cara automática', 299.99, 'Electrónica', 12, NOW() - INTERVAL 60 DAY, NOW()),
('Power Bank Anker 26800mAh', 'Batería externa de alta capacidad con 3 puertos USB y carga rápida', 59.99, 'Electrónica', 70, NOW() - INTERVAL 3 DAY, NOW()),
('Cable HDMI 2.1 3m', 'Cable HDMI 8K 60Hz, 4K 120Hz, eARC, compatible con PS5 y Xbox', 19.99, 'Electrónica', 150, NOW() - INTERVAL 55 DAY, NOW()),
('Micrófono Blue Yeti X', 'Micrófono USB profesional con 4 patrones de captación, LED', 139.99, 'Electrónica', 33, NOW() - INTERVAL 7 DAY, NOW()),

-- === ACCESORIOS (15) ===
('Mochila para Laptop 15.6"', 'Mochila antirrobo con compartimento acolchado, puerto USB externo', 45.99, 'Accesorios', 65, NOW() - INTERVAL 20 DAY, NOW()),
('Soporte para Laptop Aluminio', 'Soporte ajustable de aluminio con ventilación, plegable', 34.99, 'Accesorios', 48, NOW() - INTERVAL 18 DAY, NOW()),
('Alfombrilla XXL Gaming', 'Alfombrilla de escritorio 900x400mm, base antideslizante, borde cosido', 24.99, 'Accesorios', 90, NOW() - INTERVAL 25 DAY, NOW()),
('Funda iPad Pro 12.9"', 'Funda con teclado y trackpad integrado, ángulo ajustable', 59.99, 'Accesorios', 35, NOW() - INTERVAL 12 DAY, NOW()),
('Protector Pantalla iPhone 15', 'Vidrio templado 9H con guía de instalación, pack de 3 unidades', 14.99, 'Accesorios', 200, NOW() - INTERVAL 30 DAY, NOW()),
('Correa Apple Watch Sport', 'Correa de silicona deportiva, transpirable, múltiples colores', 12.99, 'Accesorios', 120, NOW() - INTERVAL 15 DAY, NOW()),
('Organizador de Cables', 'Kit organizador con clips, velcro y canaletas para escritorio', 18.99, 'Accesorios', 85, NOW() - INTERVAL 40 DAY, NOW()),
('Webcam Cover 3-Pack', 'Cubierta deslizante ultrafina para cámara de laptop, adhesivo 3M', 6.99, 'Accesorios', 300, NOW() - INTERVAL 50 DAY, NOW()),
('Adaptador USB-C a USB-A', 'Pack de 3 adaptadores OTG, velocidad USB 3.1, aluminio', 9.99, 'Accesorios', 175, NOW() - INTERVAL 35 DAY, NOW()),
('Limpiador de Pantallas Kit', 'Kit con spray, paño microfibra y cepillo para dispositivos', 11.99, 'Accesorios', 95, NOW() - INTERVAL 22 DAY, NOW()),
('Soporte Celular Escritorio', 'Soporte ajustable de aluminio para smartphone y tablet', 16.99, 'Accesorios', 110, NOW() - INTERVAL 10 DAY, NOW()),
('Estuche AirPods Pro', 'Funda protectora de silicona con mosquetón, resistente a golpes', 13.99, 'Accesorios', 140, NOW() - INTERVAL 8 DAY, NOW()),
('Luz LED para Monitor', 'Barra de luz USB con control táctil, temperatura de color ajustable', 39.99, 'Accesorios', 55, NOW() - INTERVAL 5 DAY, NOW()),
('Reposamuñecas Teclado Gel', 'Almohadilla ergonómica de gel con cubierta de lycra lavable', 19.99, 'Accesorios', 70, NOW() - INTERVAL 45 DAY, NOW()),
('Cable USB-C Trenzado 2m', 'Cable de carga rápida 100W PD, nylon trenzado, pack de 2', 15.99, 'Accesorios', 160, NOW() - INTERVAL 28 DAY, NOW()),

-- === MUEBLES OFICINA (15) ===
('Escritorio Standing Desk', 'Escritorio eléctrico ajustable en altura, 140x70cm, motor dual', 499.99, 'Muebles Oficina', 8, NOW() - INTERVAL 60 DAY, NOW()),
('Silla Ergonómica Premium', 'Silla de oficina con soporte lumbar, reposacabezas y brazos 4D', 389.99, 'Muebles Oficina', 12, NOW() - INTERVAL 55 DAY, NOW()),
('Monitor Arm Doble', 'Brazo articulado para 2 monitores hasta 32", montaje en escritorio', 79.99, 'Muebles Oficina', 25, NOW() - INTERVAL 30 DAY, NOW()),
('Gabinete Archivador 3 Cajones', 'Archivador metálico con cerradura, ruedas, acabado negro mate', 129.99, 'Muebles Oficina', 15, NOW() - INTERVAL 45 DAY, NOW()),
('Lámpara de Escritorio LED', 'Lámpara con brazo articulado, 5 niveles de brillo, carga USB', 44.99, 'Muebles Oficina', 40, NOW() - INTERVAL 20 DAY, NOW()),
('Reposapiés Ergonómico', 'Reposapiés ajustable con superficie texturizada antideslizante', 29.99, 'Muebles Oficina', 35, NOW() - INTERVAL 25 DAY, NOW()),
('Organizador Escritorio Madera', 'Organizador multicompartimento de bambú para papelería', 27.99, 'Muebles Oficina', 50, NOW() - INTERVAL 15 DAY, NOW()),
('Pizarra Blanca Magnética 120x90', 'Pizarra con marco de aluminio, incluye marcadores y borrador', 69.99, 'Muebles Oficina', 18, NOW() - INTERVAL 40 DAY, NOW()),
('Alfombra Protectora Silla', 'Alfombra transparente para piso, protección contra ruedas, 120x90cm', 34.99, 'Muebles Oficina', 30, NOW() - INTERVAL 35 DAY, NOW()),
('Estantería Modular 5 Niveles', 'Estantería metálica resistente, 180x90x40cm, capacidad 175kg/nivel', 89.99, 'Muebles Oficina', 10, NOW() - INTERVAL 50 DAY, NOW()),
('Cojín Lumbar Memory Foam', 'Cojín ergonómico de espuma viscoelástica con funda lavable', 24.99, 'Muebles Oficina', 55, NOW() - INTERVAL 10 DAY, NOW()),
('Bandeja Documentos 3 Pisos', 'Bandeja apilable de acrílico transparente para organizar documentos', 17.99, 'Muebles Oficina', 65, NOW() - INTERVAL 18 DAY, NOW()),
('Papelera de Oficina 15L', 'Papelera de acero inoxidable con pedal y cierre suave', 22.99, 'Muebles Oficina', 45, NOW() - INTERVAL 22 DAY, NOW()),
('Reloj de Pared Minimalista', 'Reloj silencioso de 30cm, diseño moderno, marco negro mate', 19.99, 'Muebles Oficina', 60, NOW() - INTERVAL 28 DAY, NOW()),
('Perchero de Pie Metálico', 'Perchero de 8 ganchos, base pesada antivuelco, acabado negro', 39.99, 'Muebles Oficina', 20, NOW() - INTERVAL 38 DAY, NOW()),

-- === SOFTWARE Y LICENCIAS (10) ===
('Licencia Microsoft 365 Anual', 'Suscripción anual para 1 usuario, incluye Word, Excel, PowerPoint, 1TB OneDrive', 69.99, 'Software', 500, NOW() - INTERVAL 5 DAY, NOW()),
('Licencia Adobe Creative Cloud', 'Suscripción mensual con acceso a Photoshop, Illustrator, Premiere y más', 54.99, 'Software', 300, NOW() - INTERVAL 10 DAY, NOW()),
('Antivirus Norton 360 Deluxe', 'Protección para 5 dispositivos, VPN incluida, 50GB nube, 1 año', 39.99, 'Software', 250, NOW() - INTERVAL 15 DAY, NOW()),
('Licencia Windows 11 Pro', 'Licencia digital OEM de Windows 11 Professional', 139.99, 'Software', 100, NOW() - INTERVAL 20 DAY, NOW()),
('Slack Pro Anual', 'Suscripción anual por usuario, historial ilimitado, integraciones', 84.00, 'Software', 200, NOW() - INTERVAL 25 DAY, NOW()),
('Notion Plus Anual', 'Workspace colaborativo con bloques ilimitados, API, integraciones', 96.00, 'Software', 180, NOW() - INTERVAL 12 DAY, NOW()),
('AutoCAD LT 2024', 'Licencia anual para diseño 2D profesional, compatible Windows/Mac', 440.00, 'Software', 40, NOW() - INTERVAL 30 DAY, NOW()),
('1Password Teams Anual', 'Gestor de contraseñas para equipos, 5 usuarios incluidos', 95.88, 'Software', 150, NOW() - INTERVAL 8 DAY, NOW()),
('Zoom Pro Mensual', 'Plan pro con reuniones de hasta 30h, 100 participantes, grabación', 13.33, 'Software', 400, NOW() - INTERVAL 3 DAY, NOW()),
('GitHub Copilot Individual', 'Asistente de código IA, suscripción mensual, compatible con VS Code', 10.00, 'Software', 350, NOW() - INTERVAL 2 DAY, NOW()),

-- === REDES Y CONECTIVIDAD (10) ===
('Switch TP-Link 8 Puertos Gigabit', 'Switch no gestionable, plug and play, carcasa metálica', 24.99, 'Redes', 55, NOW() - INTERVAL 40 DAY, NOW()),
('Access Point Ubiquiti U6 Pro', 'Punto de acceso WiFi 6, PoE, montaje en techo, 300+ clientes', 149.99, 'Redes', 20, NOW() - INTERVAL 35 DAY, NOW()),
('Cable Ethernet Cat6 30m', 'Cable de red blindado STP, conectores RJ45, 10Gbps', 29.99, 'Redes', 80, NOW() - INTERVAL 25 DAY, NOW()),
('Patch Panel 24 Puertos Cat6', 'Panel de parcheo para rack 19", incluye etiquetas', 44.99, 'Redes', 15, NOW() - INTERVAL 50 DAY, NOW()),
('NAS Synology DS224+', 'Servidor NAS 2 bahías, Intel Celeron, 2GB RAM, ideal para PYMES', 299.99, 'Redes', 9, NOW() - INTERVAL 30 DAY, NOW()),
('Adaptador WiFi USB AC1300', 'Adaptador inalámbrico dual band con antena externa, USB 3.0', 29.99, 'Redes', 65, NOW() - INTERVAL 20 DAY, NOW()),
('Rack de Pared 6U', 'Gabinete de pared para redes, ventilado, con cerradura', 89.99, 'Redes', 10, NOW() - INTERVAL 45 DAY, NOW()),
('Crimpeadora RJ45 Profesional', 'Herramienta de crimpado con pelador y cortador integrado', 19.99, 'Redes', 40, NOW() - INTERVAL 55 DAY, NOW()),
('Pack 100 Conectores RJ45 Cat6', 'Conectores blindados para cable de red, chapado en oro', 12.99, 'Redes', 120, NOW() - INTERVAL 15 DAY, NOW()),
('Tester de Cable de Red', 'Probador de continuidad para cables RJ45 y RJ11, LCD', 14.99, 'Redes', 50, NOW() - INTERVAL 10 DAY, NOW()),

-- === PAPELERÍA Y OFICINA (10) ===
('Resma Papel A4 500 hojas', 'Papel blanco 80g/m², para impresión láser e inkjet', 7.99, 'Papelería', 200, NOW() - INTERVAL 5 DAY, NOW()),
('Pack Bolígrafos Pilot G2 12u', 'Bolígrafos de gel retráctiles, punta 0.7mm, tinta negra', 14.99, 'Papelería', 85, NOW() - INTERVAL 10 DAY, NOW()),
('Cuaderno Moleskine A5', 'Cuaderno de pasta dura, 240 páginas, papel marfil 70g', 19.99, 'Papelería', 60, NOW() - INTERVAL 15 DAY, NOW()),
('Post-it Super Sticky 12 Pack', 'Notas adhesivas 76x76mm, colores surtidos, 90 hojas c/u', 16.99, 'Papelería', 100, NOW() - INTERVAL 20 DAY, NOW()),
('Grapadora Heavy Duty', 'Grapadora de alto rendimiento, capacidad 100 hojas, ergonómica', 24.99, 'Papelería', 30, NOW() - INTERVAL 30 DAY, NOW()),
('Cinta Adhesiva Scotch 6 Pack', 'Cinta transparente 19mm x 33m, dispensador incluido', 8.99, 'Papelería', 130, NOW() - INTERVAL 25 DAY, NOW()),
('Carpetas Colgantes 25u', 'Carpetas tamaño oficio con visor y etiquetas, colores surtidos', 21.99, 'Papelería', 45, NOW() - INTERVAL 35 DAY, NOW()),
('Marcadores Sharpie 24 Colores', 'Set de marcadores permanentes de punta fina, resistentes al agua', 18.99, 'Papelería', 55, NOW() - INTERVAL 12 DAY, NOW()),
('Tijeras de Oficina 21cm', 'Tijeras de acero inoxidable con mango ergonómico antideslizante', 7.99, 'Papelería', 75, NOW() - INTERVAL 40 DAY, NOW()),
('Calculadora Casio Científica', 'Calculadora científica 417 funciones, pantalla natural, solar', 24.99, 'Papelería', 40, NOW() - INTERVAL 18 DAY, NOW()),

-- === GAMING (10) ===
('Control PS5 DualSense', 'Control inalámbrico con retroalimentación háptica y gatillos adaptativos', 69.99, 'Gaming', 30, NOW() - INTERVAL 8 DAY, NOW()),
('Headset HyperX Cloud III', 'Auriculares gaming con micrófono, DTS Spatial Audio, 53mm drivers', 99.99, 'Gaming', 25, NOW() - INTERVAL 12 DAY, NOW()),
('Mouse Gaming Razer DeathAdder V3', 'Mouse ultraligero 59g, sensor Focus Pro 30K, switches ópticas', 89.99, 'Gaming', 35, NOW() - INTERVAL 6 DAY, NOW()),
('Teclado Gaming Corsair K70', 'Teclado mecánico RGB, switches Cherry MX Red, reposamuñecas', 159.99, 'Gaming', 20, NOW() - INTERVAL 15 DAY, NOW()),
('Monitor Gaming ASUS 27" 165Hz', 'Monitor IPS 1440p, 1ms GTG, G-Sync Compatible, HDR10', 329.99, 'Gaming', 14, NOW() - INTERVAL 20 DAY, NOW()),
('Silla Gaming Secretlab Titan', 'Silla premium con respaldo reclinable, soporte lumbar 4D, piel sintética', 449.99, 'Gaming', 7, NOW() - INTERVAL 25 DAY, NOW()),
('Capturadora Elgato HD60 X', 'Capturadora de video 4K30 HDR, passthrough 4K60, USB 3.0', 159.99, 'Gaming', 18, NOW() - INTERVAL 10 DAY, NOW()),
('Gamepad Xbox Elite Series 2', 'Control premium con palancas ajustables, gatillos de pelo, estuche', 179.99, 'Gaming', 0, NOW() - INTERVAL 30 DAY, NOW()),
('Streaming Deck Elgato 15 Teclas', 'Controlador LCD con teclas personalizables para streaming', 149.99, 'Gaming', 22, NOW() - INTERVAL 5 DAY, NOW()),
('Base Refrigerante Laptop RGB', 'Base con 6 ventiladores, pantalla LCD, control de velocidad, RGB', 39.99, 'Gaming', 50, NOW() - INTERVAL 18 DAY, NOW()),

-- === ALMACENAMIENTO (10) ===
('Disco Duro Externo 4TB WD', 'HDD portátil USB 3.0, compatible Windows y Mac, negro', 109.99, 'Almacenamiento', 35, NOW() - INTERVAL 22 DAY, NOW()),
('Memoria USB 128GB SanDisk', 'USB 3.2 Gen 1, velocidad hasta 400 MB/s, compacta', 18.99, 'Almacenamiento', 100, NOW() - INTERVAL 15 DAY, NOW()),
('SSD Externo Samsung T7 1TB', 'SSD portátil USB 3.2, velocidad 1050 MB/s, resistente a caídas', 109.99, 'Almacenamiento', 28, NOW() - INTERVAL 10 DAY, NOW()),
('Tarjeta MicroSD 256GB Samsung', 'MicroSDXC EVO Select, UHS-I U3, V30, con adaptador SD', 27.99, 'Almacenamiento', 80, NOW() - INTERVAL 8 DAY, NOW()),
('HDD Interno Seagate 2TB', 'Disco duro 3.5" SATA III, 7200 RPM, caché 256MB', 54.99, 'Almacenamiento', 40, NOW() - INTERVAL 30 DAY, NOW()),
('SSD Kingston A400 480GB', 'SSD SATA III 2.5", velocidad lectura 500 MB/s, ideal para upgrade', 39.99, 'Almacenamiento', 55, NOW() - INTERVAL 25 DAY, NOW()),
('NVMe WD Black SN850X 1TB', 'SSD NVMe PCIe 4.0 con disipador, lectura 7300 MB/s, para gaming', 99.99, 'Almacenamiento', 30, NOW() - INTERVAL 12 DAY, NOW()),
('Carcasa Disco Duro USB 3.0', 'Carcasa externa para HDD/SSD 2.5" SATA, sin herramientas', 12.99, 'Almacenamiento', 90, NOW() - INTERVAL 40 DAY, NOW()),
('Memoria RAM DDR5 32GB', 'Kit 2x16GB DDR5 5600MHz CL36, perfiles XMP 3.0', 89.99, 'Almacenamiento', 3, NOW() - INTERVAL 5 DAY, NOW()),
('Docking Station HDD Dual', 'Base para clonar y leer discos 2.5"/3.5" SATA, USB 3.0', 34.99, 'Almacenamiento', 25, NOW() - INTERVAL 35 DAY, NOW());
